# from defines the base image
FROM neo4j:latest
MAINTAINER Casey Billman <caseybillman@gmail.com>

CMD [ "wget", "https://github.com/neo4j-contrib/m2/blob/master/releases/org/neo4j/neo4j-spatial/0.23-neo4j-3.0.4/neo4j-spatial-0.23-neo4j-3.0.4-server-plugin.jar?raw=true" ]
